[project]
name = "pyaccessibility"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "macapptree>=0.0.2",
    "streamlit>=1.50.0",
]
